# build environment
# FROM node:13-alpine as build
# WORKDIR /app
# ENV PATH /app/node_modules/.bin:$PATH
# COPY package.json /app/package.json
# RUN npm install
# RUN npm install react-scripts@3.0.1 -g
# COPY . /app
# RUN npm run build

FROM node:16-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
#COPY package-lock.json ./
COPY ./ ./
RUN npm install --global pm2
RUN npm install
RUN npm run build

EXPOSE 3001

USER node
CMD [ "pm2-runtime", "npm", "--", "start" ]
# production environment
# FROM nginx
# COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
# COPY --from=build /app/build /usr/share/nginx/html
# EXPOSE 80

